package com.yrris.coddy.ai.tool;

import com.yrris.coddy.constant.AppConstant;
import com.yrris.coddy.exception.BusinessException;
import com.yrris.coddy.exception.ErrorCode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Pre-creates the fixed project skeleton for React+Vite projects.
 * These files are NOT generated by AI — they are pinned to stable versions
 * to ensure consistent builds (problem standardization).
 */
@Component
public class ReactViteProjectInitializer {

    private static final Logger log = LoggerFactory.getLogger(ReactViteProjectInitializer.class);

    private static final String PACKAGE_JSON = """
            {
              "name": "coddy-react-app",
              "private": true,
              "version": "1.0.0",
              "type": "module",
              "scripts": {
                "dev": "vite",
                "build": "vite build",
                "preview": "vite preview"
              },
              "dependencies": {
                "react": "^19.0.0",
                "react-dom": "^19.0.0",
                "react-router-dom": "^7.1.0"
              },
              "devDependencies": {
                "@vitejs/plugin-react": "^4.3.0",
                "vite": "^6.0.0"
              }
            }
            """;

    private static final String VITE_CONFIG_JS = """
            import { defineConfig } from 'vite'
            import react from '@vitejs/plugin-react'

            export default defineConfig({
              plugins: [react()],
              base: './'
            })
            """;

    private static final String INDEX_HTML = """
            <!doctype html>
            <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>Coddy React App</title>
            </head>
            <body>
              <div id="root"></div>
              <script type="module" src="/src/main.jsx"></script>
            </body>
            </html>
            """;

    public void initializeProject(long appId) {
        String baseDir = AppConstant.CODE_OUTPUT_ROOT_DIR + "/react_vite_" + appId;
        Path basePath = Paths.get(baseDir);

        try {
            Files.createDirectories(basePath.resolve("src"));
            Files.createDirectories(basePath.resolve("public"));

            writeIfNotExists(basePath.resolve("package.json"), PACKAGE_JSON);
            writeIfNotExists(basePath.resolve("vite.config.js"), VITE_CONFIG_JS);
            writeIfNotExists(basePath.resolve("index.html"), INDEX_HTML);

            log.info("Initialized React+Vite project skeleton for appId={}", appId);
        } catch (IOException e) {
            throw new BusinessException(ErrorCode.INTERNAL_ERROR,
                    "Failed to initialize React project skeleton: " + e.getMessage());
        }
    }

    private void writeIfNotExists(Path filePath, String content) throws IOException {
        if (!Files.exists(filePath)) {
            Files.writeString(filePath, content, StandardCharsets.UTF_8);
        }
    }
}
